name: Build and Tag Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - id: "auth"
        name: GCP Authentication
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_SA_TOKEN_FILE }}
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: "deep-dynamics-460610-u8"

      - name: List files in workspace
        run: pwd

      - name: Upload file to GCS
        run: |
          gsutil cp ${{ github.workspace }}/README.md gs://test-neela-bucket/myfolder/

      - name: Authorize Docker Push
        run: gcloud auth configure-docker

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Build Tag in jfrog and push Docker Image to gcp
        env:
          #IMAGE_NAME: neela.jfrog.io/test-docker/jfrog-docker-example-image:${{ github.run_number }}
          IMAGE_NAME: europe-west1-docker.pkg.dev/deep-dynamics-460610-u8/test-docker-cloudrun:${{ github.run_number }}
        run: |
          docker build -t redisdemo
          echo "build done test"
          docker tag redisdemo "${IMAGE_NAME}"
          docker push $IMAGE_NAME
          echo "build and push done"

#      - name: Publish Build info With JFrog CLI
#        env:
#          # Generated and maintained by GitHub
#          JFROG_CLI_BUILD_NAME: jfrog-docker-build-example
#          # JFrog organization secret
#          JFROG_CLI_BUILD_NUMBER : ${{ github.run_number }}
#        run: |
#          # Export the build name and build nuber
#          # Collect environment variables for the build
#          jf rt build-collect-env
#          # Collect VCS details from git and add them to the build
#          jf rt build-add-git
#          # Publish build info
#          jf rt build-publish